.PHONY: clean All

All:
	@echo "----------Building project:[ Fraction - Debug ]----------"
	@cd "Fraction" && "$(MAKE)" -f  "Fraction.mk"
clean:
	@echo "----------Cleaning project:[ Fraction - Debug ]----------"
	@cd "Fraction" && "$(MAKE)" -f  "Fraction.mk" clean
